### ISSUE TITLE
[Feature] Make this plugin compatible with Sylius 1.9

### ISSUE THREAD

**Issue by corneagigi** [synolia/SyliusAkeneoPlugin#60]
Unfortunately, the current version is not compatible with Sylius 1.9. When do you plan to make it compatible?

**Comment by oallain** [comment]
Hello,

I hope for next week, or the following week.

**Comment by oallain** [comment]
Hello,

https://github.com/synolia/SyliusAkeneoPlugin/releases/tag/v2.0.0 solve this issue. 
V2 is compatible wiith Sylius 1.9 🚀
