### ISSUE TITLE
[Bug] FamilyVariationAxeProcessor doesn't remove old axes from variationAxes

### ISSUE THREAD

**Issue by gbelorgey** [synolia/SyliusAkeneoPlugin#87]
**Describe the bug**
When the variationAxes of a family are modified in Akeneo, the plugin only adds new axes in `akeneo_product_group`. Old axes are never purged from the variationAxes array.

**To Reproduce**
1. Sync families : `bin/console akeneo:import:families`
2. In database, pick any entry in `akeneo_product_group` and set a fake `variationAxes` value (ex : `a:1:{i:0;s:10:"dummy_axis";}`
3. Sync families again : `bin/console akeneo:import:families`
4. Check your entry in `akeneo_product_group` :  `variationAxes` now has the correct axes *and* `dummy_axis` remains.

**Expected behavior**
When an attribute is no longer used as a variation axis, it should be purged from `akeneo_product_group` when families are imported.

**Comment by TheGrimmChester** [comment]
Fixed in v3.0.0
